<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VoiceDentalReceptionist</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Config -->
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />

    <!-- Foundry -->
  
    <PackageReference Include="Azure.AI.Extensions.OpenAI" Version="2.1.0-beta.4" />
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />

    <PackageReference Include="OpenAI" Version="2.9.1" />

   
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.42.0" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="data\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
